quarkus.http.port=8081
quarkus.rest-client."auth-service-api".url=http://localhost:8082
quarkus.rest-client."auth-service-api".connect-timeout=3000
quarkus.rest-client."auth-service-api".read-timeout=10000

# Enable CORS globally for development
quarkus.http.cors.enabled=true

# Allow requests originating from your Vite frontend port
quarkus.http.cors.origins=*

# # Allow the specific HTTP request methods your Gateway utilizes
quarkus.http.cors.methods=*

# # Crucial: Allow the Authorization and Content-Type headers through the firewall
quarkus.http.cors.headers=*
